apiVersion: v1
kind: Service
metadata:
  name: firstapp-service
  labels:
    app: firstapp
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: firstapp
  type: NodePort
